# Generated by Django 4.1.7 on 2023-03-27 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("destinations", "0002_hotel"),
    ]

    operations = [
        migrations.DeleteModel(name="Hotel",),
    ]
