# Generated by Django 4.1.7 on 2023-03-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Travel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.CharField(max_length=2085)),
                ("title", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=3000)),
            ],
        ),
    ]
